version : '2'
services:
    web:
      build: .
      command: npm start
      volumes:
       - ./src:/usr/app/src
      ports:
       - "4000:9000"
      depends_on:
       - postgres
    postgres:
      image: postgres
      ports:
       - "54320:5432"
      environment:
        POSTGRES_USER: saif10p
        POSTGRES_PASSWORD: 10pearls
        POSTGRES_DB: fullstackdb
      volumes:
       - postgresql:/var/lib/postgresql

volumes:
  postgresql: